name: hexlet-check

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: make lint
        
      - name: Hexlet project check
        uses: hexlet/project-action@release
        
